### ISSUE TITLE
ashic-data pack error

### ISSUE THREAD

**Issue by BenxiaHu** [wmalab/ASHIC#6]
Hello, I am trying to use ASHIC to predict haplotype Hi-C matrices. I ran ashic-data bin-hicpro to obtain:
merge_chr1_0_0_10000.npy  merge_chr1_1_1_10000.npy  merge_chr1_2_0_10000.npy
merge_chr1_1_0_10000.npy  merge_chr1_1_2_10000.npy  merge_chr1_2_2_10000.npy
Next, I am trying to run ashic-data pack to get the contact matrices: 
```
i=1
ashic-data pack /data/H3K27ac_ashic/chr${i} --prefix merge_chr${i} /data/H3K27ac_ashic/chr${i}_ASHIC
```
However, i got the following errors: 

/data/anaconda3/envs/ashic/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Traceback (most recent call last):
  **File "/data/anaconda3/envs/ashic/bin/ashic-data", line 8, in <module>**
    sys.exit(cli())
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/anaconda3/envs/ashic/lib/python2.7/site-packages/ashic/cli/ashic_data.py", line 528, in prepare_data
    **obs[f[a1]+f[a2]] = np.load(file[0])**
IndexError: list index out of range
/data/anaconda3/envs/ashic/lib/python2.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes

do you know how to address this issue?
Best,

**Comment by tye42** [comment]
I am so sorry for the late reply. Please try use the option `--mat=1`, `--pat=2`, and `--amb=0` to define the allele flag of maternal-specific, paternal-specific, and allele-ambiguous reads, respectively.
